SELECT PRODUCT_CODE
     , SUM(OFFLINE.SALES_AMOUNT * PRICE) AS SALES
  FROM PRODUCT
  JOIN OFFLINE_SALE AS OFFLINE
    ON PRODUCT.PRODUCT_ID = OFFLINE.PRODUCT_ID
 GROUP BY PRODUCT_CODE
 ORDER BY SALES DESC, PRODUCT_CODE
