-- 조건에 부합하는 중고거래 댓글 조회하기

-- LEFT JOIN
SELECT
    BOARD.TITLE,
    BOARD.BOARD_ID,
    REPLY.REPLY_ID,
    REPLY.WRITER_ID,
    REPLY.CONTENTS,
    DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM
    USED_GOODS_BOARD AS BOARD
LEFT OUTER JOIN
    USED_GOODS_REPLY AS REPLY
    ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE
    YEAR(BOARD.CREATED_DATE) = '2022'
    AND
    MONTH(BOARD.CREATED_DATE) = '10'
    AND
    REPLY.CREATED_DATE IS NOT NULL
ORDER BY
    REPLY.CREATED_DATE,
    BOARD.TITLE;


-- INNER JOIN

SELECT
    BOARD.TITLE,
    BOARD.BOARD_ID,
    REPLY.REPLY_ID,
    REPLY.WRITER_ID,
    REPLY.CONTENTS,
    DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM
    USED_GOODS_BOARD AS BOARD
INNER JOIN
    USED_GOODS_REPLY AS REPLY
    ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE
    YEAR(BOARD.CREATED_DATE) = '2022'
    AND
    MONTH(BOARD.CREATED_DATE) = '10'
ORDER BY
    REPLY.CREATED_DATE,
    BOARD.TITLE;

/*
    처음에 LEFT JOIN 으로 풀었다가 뭔가 INNER JOIN 으로 될 것 같아서 둘 다 해봤다.
    LEFT JOIN: SELECT 에서 지정한 열의 데이터가 NULL 이어도 출력되서 REPLY.CREATED_DATE IS NOT NULL 조건을 추가해줘야 했다.DATE_FORMAT
    INNER JOIN: 내부 JOIN 은 두 테이블의 모두 데이터가 있어야만 결과로 나와서 편하다.

    아직 각 JOIN 벤 다이어그램이 바로바로 안떠올라서 좀 헷갈린다...
*/