-- 카테고리 별 도서 판매량 집계하기

SELECT CATEGORY
     , SUM(BS.SALES) AS TOTAL_SALES
  FROM BOOK AS B
 INNER JOIN BOOK_SALES AS BS
    ON B.BOOK_ID = BS.BOOK_ID
 WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
 GROUP BY CATEGORY
 ORDER BY CATEGORY
