-- 성분으로 구분한 아이스크림 총 주문량

SELECT II.INGREDIENT_TYPE
     , SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
  FROM FIRST_HALF AS FH
 INNER JOIN ICECREAM_INFO AS II
    ON FH.FLAVOR = II.FLAVOR
 GROUP BY II.INGREDIENT_TYPE
 ORDER BY TOTAL_ORDER